### ISSUE TITLE
Cant connect to 

### ISSUE THREAD

**Issue by oberos** [jamesmbull/sp-bash#1]
When i use Your script i cant connect. I modify it to debug where it fails. It turn out that it gets security token but fail to obtain cookies. I add dump to file in this line

curl -c cookies -X POST -d @stoken https://****.sharepoint.com/_forms/default.aspx?wa=wsignin1.0 -o my_file

And when i open my file i see something like this:

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/">here</a>.</h2>
</body></html>

strange is that i have some data in cookies file.

**Comment by jamesmbull** [comment]
Sorry, I never saw this issue posted! I get that notice, too. I think it might be due to a redirect after the appropriate cookies are written. At any rate, it doesn't keep the script from successfully completing for me.
